---

- name: Gather general variables
  include_vars: main.yml

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true

- include_tasks: install-pkgs.yml
  when: not freeipa_from_sources

- include_tasks: from_sources/main.yml
  when: freeipa_from_sources
