---

- name: Build FreeIPA
  args:
    chdir: "{{ freeipa_install_dir }}/build/freeipa-release-{{ freeipa_version_src_schema }}"
  shell: "autoreconf -i -f && ./configure {{ freeipa_build_options | join(' ') }}"
  when: >
        (freeipa_checksum_catalog.changed) or
        (freeipa_source_files.changed) or
        (freeipa_patches.changed) or
        (freeipa_force_build)
  register: freeipa_build
